version: '3.1'

services:

  db:
    container_name: campaign-finance
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
        - 54322:5432
